Added my first solution.
mate-academy/jv-web-security pull request #341
Opened 2022-09-21 12:38 UTC by vadimkik2

2022-09-21 14:20 UTC, Maksym-Korkosh approved these changes

2022-09-21 14:32 UTC, Mihael0204 approved these changes

2022-09-21 14:40 UTC, Sofasmile requested changes
fix: 
- drivers/add.jsp
- add changes to web.xml

2022-09-21 14:40 UTC, Sofasmile commented on src/main/java/taxi/controller/authentication/LogoutController.java
> +        response.sendRedirect("/login");
use context path

2022-09-22 09:24 UTC, Sofasmile requested changes
![image](https://user-images.githubusercontent.com/36365171/191710436-997286a5-e9de-4d6d-bdd8-04d0f0f92b0e.png)

2022-09-22 13:06 UTC, closed without merging

2022-09-22 13:28 UTC, Sofasmile requested changes

2022-09-22 13:28 UTC, Sofasmile commented on src/main/webapp/WEB-INF/views/drivers/add.jsp
> +            <input type="text" name="password" form="driver" required>
```suggestion
            <input type="password" name="password" form="driver" required>
```