Hw jv web security
mate-academy/jv-web-security pull request #462
Opened 2023-01-18 07:26 UTC by DanyloBorysenko

2023-01-18 21:57 UTC, aleksandr-bevza requested changes

2023-01-18 21:57 UTC, aleksandr-bevza commented on src/main/resources/init_db.sql
> +                            `login` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
If we want to find driver by login - it should be unique.

2023-01-18 21:57 UTC, aleksandr-bevza commented on src/main/java/taxi/service/AuthenticationServiceImpl.java
> +        if (driver.get().getPassword().equals(password)) {
```suggestion
        if (driver.isPresent() && driver.get().getPassword().equals(password)) {
```

2023-01-18 21:57 UTC, aleksandr-bevza commented on src/main/java/taxi/service/AuthenticationServiceImpl.java
> +        }
```suggestion
```

2023-01-19 14:04 UTC, aaananas approved these changes

2025-09-15 12:57 UTC, closed without merging