added java homework web security solution
mate-academy/jv-web-security pull request #61
Opened 2021-07-24 22:00 UTC by Basilius-Third

2021-07-24 22:09 UTC, Veronika-Alekseienko approved these changes
Very good!!🔥🔥🔥

2021-07-24 22:29 UTC, SeReNb26 requested changes

2021-07-24 22:29 UTC, SeReNb26 commented on src/main/java/mate/controller/car/driver/GetMyCurrentCarsController.java
> +        req.getRequestDispatcher("/WEB-INF/views/cars/all.jsp").forward(req, resp);
cars/all -> cars (best practice), same in other places

2021-07-24 22:29 UTC, SeReNb26 commented on src/main/java/mate/controller/driver/AddDriverController.java
> +        Driver driver = new Driver(name, licenceNumber, login, password);
licenceNumber -> licenseNumber

2021-07-24 22:29 UTC, SeReNb26 commented on src/main/java/mate/dao/DriverDaoImpl.java
>          String licenseNumber = resultSet.getString("license_number");
change licence to license anywhere

2021-07-24 22:29 UTC, SeReNb26 commented on src/main/java/mate/model/Driver.java
> +
Я бы расставил конструкты от меньше количества параметров, к большему. 
Ты можешь в самом большом конструкторе прописать 
this(name, licenseNumber, login, password);
this.id = id;

2021-07-24 22:29 UTC, SeReNb26 commented on src/main/webapp/WEB-INF/views/login.jsp
> +<%@ page contentType="text/html;charset=UTF-8" language="java" %>
Удалить везде language="java". Оно deprecated

2021-07-24 22:47 UTC, SeReNb26 approved these changes

2021-07-26 06:38 UTC, Sofasmile requested changes
good job)

2021-07-26 06:38 UTC, Sofasmile commented on src/main/java/mate/service/AuthenticationServiceImpl.java
> +        if (password.equals(driver.get().getPassword())) {
what will happen if Optional is empty?

2021-07-26 09:23 UTC, Sofasmile approved these changes

2021-11-16 17:04 UTC, closed without merging